"""ChatBI 数据源相关常量。"""

from __future__ import annotations

# 预处理 Worker 与 API 入队共用 Redis Stream 名称。
CHATBI_PREPROCESS_TASK_STREAM = "chatbi_preprocess_tasks"
# 预处理任务投递到 Stream 时的消息类型。
CHATBI_PREPROCESS_STREAM_TASK_TYPE = "CHATBI_PREPROCESS"
# PostgreSQL 默认 schema。
CHATBI_DEFAULT_SCHEMA_NAME = "public"
# execute-sql 单次返回行数上限，与连接器截断一致。
CHATBI_EXECUTE_SQL_MAX_ROWS = 500
# execute-sql 单次语句执行超时，避免慢 SQL 长时间占用连接。
CHATBI_EXECUTE_SQL_TIMEOUT_SECONDS = 30.0
# 结构采集总超时与样本采集限制，避免预处理阶段拖垮外部业务库。
CHATBI_STRUCTURE_LOAD_TIMEOUT_SECONDS = 60.0
CHATBI_STRUCTURE_SAMPLE_TIMEOUT_SECONDS = 2.0
CHATBI_STRUCTURE_SAMPLE_TABLE_LIMIT = 20
CHATBI_STRUCTURE_SAMPLE_COLUMN_LIMIT = 80
# ChatBI pgvector 表结构固定维度；维度调整必须走新迁移。
CHATBI_VECTOR_DIMENSIONS = 1024
# 预处理 Worker 每次认领空闲消息数量。
CHATBI_PREPROCESS_WORKER_CLAIM_IDLE_COUNT = 20

__all__ = [
    "CHATBI_DEFAULT_SCHEMA_NAME",
    "CHATBI_EXECUTE_SQL_MAX_ROWS",
    "CHATBI_EXECUTE_SQL_TIMEOUT_SECONDS",
    "CHATBI_PREPROCESS_TASK_STREAM",
    "CHATBI_PREPROCESS_WORKER_CLAIM_IDLE_COUNT",
    "CHATBI_PREPROCESS_STREAM_TASK_TYPE",
    "CHATBI_STRUCTURE_LOAD_TIMEOUT_SECONDS",
    "CHATBI_STRUCTURE_SAMPLE_COLUMN_LIMIT",
    "CHATBI_STRUCTURE_SAMPLE_TABLE_LIMIT",
    "CHATBI_STRUCTURE_SAMPLE_TIMEOUT_SECONDS",
    "CHATBI_VECTOR_DIMENSIONS",
]
