"""ChatBI 问数 SSE 事件名与编排常量。"""

CHATBI_SSE_STARTED = "started"
CHATBI_SSE_REWRITTEN_QUESTION = "rewritten_question"
CHATBI_SSE_BUSINESS_KNOWLEDGE_RECALL = "business_knowledge_recall"
CHATBI_SSE_INTENT = "intent"
CHATBI_SSE_SCHEMA_LINKING = "schema_linking"
CHATBI_SSE_SCHEMA_SELECTED = "schema_selected"
CHATBI_SSE_QSQL_RECALL = "qsql_recall"
CHATBI_SSE_SQL_CANDIDATES = "sql_candidates"
CHATBI_SSE_SQL = "sql"
CHATBI_SSE_SQL_VALIDATE = "sql_validate"
CHATBI_SSE_DATA = "data"
CHATBI_SSE_SUMMARY = "summary"
CHATBI_SSE_COMPLETED = "completed"
CHATBI_SSE_CLARIFICATION_REQUIRED = "clarification_required"
CHATBI_SSE_VALUE_FOUNDING = "value_founding"
CHATBI_SSE_VALUE_SEARCH = "value_search"
CHATBI_SSE_RAG_KNOWLEDGE_RECALL = "rag_knowledge_recall"
CHATBI_SSE_SQL_GROUP_AUDIT = "sql_group_audit"
CHATBI_SSE_FAILED = "failed"

CHATBI_PAGE_DEFAULT_SIZE = 20
CHATBI_PAGE_MAX_SIZE = 100
CHATBI_CLARIFICATION_REDIS_PREFIX = "chatbi:clarification"
CHATBI_CLARIFICATION_TTL_SECONDS = 900
CHATBI_SCHEMA_SELECT_TOP_K = 20
CHATBI_QSQL_RECALL_TOP_N = 5
CHATBI_QSQL_RECALL_CANDIDATE_TOP_N = 40
CHATBI_QSQL_RECALL_FILTERED_CANDIDATE_TOP_N = 200
CHATBI_BUSINESS_KNOWLEDGE_TOP_K = 5
CHATBI_BUSINESS_KNOWLEDGE_GLOBAL_LIMIT = 50
CHATBI_SQL_FIX_MAX_ATTEMPTS = 1
CHATBI_QUERY_HISTORY_LIMIT = 12
# 问数可参与意图选择的数据源上限；绑定数据源不受该上限影响。
CHATBI_QUERY_DATASOURCE_CANDIDATE_LIMIT = 200
# query_log 中保存的数据预览行数。
CHATBI_RESULT_PREVIEW_MAX_ROWS = 20
# 结果总结阶段注入 LLM 的样本行数上限（用户 SSE data 仍返回完整结果集）
CHATBI_SUMMARY_PREVIEW_MAX_ROWS = 50
CHATBI_SUMMARY_MISSING_DATASOURCE = "缺少相关数据源"
CHATBI_CLARIFICATION_SKIPPED_MARKER = "（用户选择跳过澄清）"

CHATBI_QUERY_OUTCOME_SERVICE_ERROR = "service_error"
CHATBI_QUERY_OUTCOME_LLM_ERROR = "llm_error"
CHATBI_QUERY_OUTCOME_UNHANDLED_ERROR = "unhandled_error"
CHATBI_QUERY_OUTCOME_MISSING_DATASOURCE = "missing_datasource"
CHATBI_QUERY_OUTCOME_SCHEMA_NOT_READY = "schema_not_ready"
CHATBI_QUERY_OUTCOME_TEXT2SQL_FAILED = "text2sql_failed"
CHATBI_QUERY_OUTCOME_SQL_EXECUTE_FAILED = "sql_execute_failed"
CHATBI_QUERY_OUTCOME_SUCCESS = "success"

# 问数意图 LLM JSON 字段名（与 INTENT prompt 约定一致）
CHATBI_INTENT_JSON_FIELD_CHOICE = "choice"
CHATBI_INTENT_JSON_FIELD_INTENT = "intent"
CHATBI_INTENT_JSON_FIELD_BRIEF = "brief"
CHATBI_INTENT_JSON_FIELD_DATASOURCE_ID = "datasource_id"
CHATBI_INTENT_JSON_FIELD_CLARIFICATION_QUESTION = "clarification_question"
CHATBI_INTENT_JSON_FIELD_OPTIONS = "options"

__all__ = [
    "CHATBI_CLARIFICATION_SKIPPED_MARKER",
    "CHATBI_INTENT_JSON_FIELD_BRIEF",
    "CHATBI_INTENT_JSON_FIELD_CHOICE",
    "CHATBI_INTENT_JSON_FIELD_CLARIFICATION_QUESTION",
    "CHATBI_INTENT_JSON_FIELD_DATASOURCE_ID",
    "CHATBI_INTENT_JSON_FIELD_INTENT",
    "CHATBI_INTENT_JSON_FIELD_OPTIONS",
    "CHATBI_BUSINESS_KNOWLEDGE_GLOBAL_LIMIT",
    "CHATBI_BUSINESS_KNOWLEDGE_TOP_K",
    "CHATBI_PAGE_DEFAULT_SIZE",
    "CHATBI_PAGE_MAX_SIZE",
    "CHATBI_CLARIFICATION_REDIS_PREFIX",
    "CHATBI_CLARIFICATION_TTL_SECONDS",
    "CHATBI_SSE_BUSINESS_KNOWLEDGE_RECALL",
    "CHATBI_SSE_CLARIFICATION_REQUIRED",
    "CHATBI_SSE_COMPLETED",
    "CHATBI_SSE_DATA",
    "CHATBI_SSE_FAILED",
    "CHATBI_SSE_INTENT",
    "CHATBI_SSE_QSQL_RECALL",
    "CHATBI_SSE_SCHEMA_SELECTED",
    "CHATBI_SSE_SQL_CANDIDATES",
    "CHATBI_SSE_REWRITTEN_QUESTION",
    "CHATBI_SSE_VALUE_FOUNDING",
    "CHATBI_SSE_VALUE_SEARCH",
    "CHATBI_SSE_RAG_KNOWLEDGE_RECALL",
    "CHATBI_SSE_SQL",
    "CHATBI_SSE_SQL_GROUP_AUDIT",
    "CHATBI_SSE_STARTED",
    "CHATBI_SSE_SUMMARY",
    "CHATBI_QSQL_RECALL_TOP_N",
    "CHATBI_QSQL_RECALL_CANDIDATE_TOP_N",
    "CHATBI_QSQL_RECALL_FILTERED_CANDIDATE_TOP_N",
    "CHATBI_SCHEMA_SELECT_TOP_K",
    "CHATBI_SQL_FIX_MAX_ATTEMPTS",
    "CHATBI_QUERY_HISTORY_LIMIT",
    "CHATBI_QUERY_DATASOURCE_CANDIDATE_LIMIT",
    "CHATBI_QUERY_OUTCOME_LLM_ERROR",
    "CHATBI_QUERY_OUTCOME_MISSING_DATASOURCE",
    "CHATBI_QUERY_OUTCOME_SCHEMA_NOT_READY",
    "CHATBI_QUERY_OUTCOME_SERVICE_ERROR",
    "CHATBI_QUERY_OUTCOME_SQL_EXECUTE_FAILED",
    "CHATBI_QUERY_OUTCOME_SUCCESS",
    "CHATBI_QUERY_OUTCOME_TEXT2SQL_FAILED",
    "CHATBI_QUERY_OUTCOME_UNHANDLED_ERROR",
    "CHATBI_RESULT_PREVIEW_MAX_ROWS",
    "CHATBI_SUMMARY_PREVIEW_MAX_ROWS",
    "CHATBI_SUMMARY_MISSING_DATASOURCE",
]
