"""ChatBI 后台任务状态常量。"""

CHATBI_TASK_STATUS_PENDING = "PENDING"
CHATBI_TASK_STATUS_RUNNING = "RUNNING"
CHATBI_TASK_STATUS_SUCCESS = "SUCCESS"
CHATBI_TASK_STATUS_FAILED = "FAILED"

CHATBI_ACTIVE_TASK_STATUSES = (
    CHATBI_TASK_STATUS_PENDING,
    CHATBI_TASK_STATUS_RUNNING,
)
CHATBI_ACTIVE_TASK_STATUS_SQL = (
    f"status IN ('{CHATBI_TASK_STATUS_PENDING}', '{CHATBI_TASK_STATUS_RUNNING}')"
)

__all__ = [
    "CHATBI_ACTIVE_TASK_STATUSES",
    "CHATBI_ACTIVE_TASK_STATUS_SQL",
    "CHATBI_TASK_STATUS_FAILED",
    "CHATBI_TASK_STATUS_PENDING",
    "CHATBI_TASK_STATUS_RUNNING",
    "CHATBI_TASK_STATUS_SUCCESS",
]
