"""Chat 相关常量。"""

from __future__ import annotations

CHAT_DEFAULT_APP_NAME = "默认 Chat"
CHAT_DEFAULT_PAGE_SIZE = 20
CHAT_MAX_PAGE_SIZE = 100
CHAT_MAX_TITLE_LENGTH = 100
CHAT_MAX_APP_DESCRIPTION_LENGTH = 500
CHAT_MAX_PROJECT_NAME_LENGTH = 100
CHAT_MAX_MESSAGE_LENGTH = 4000
CHAT_MAX_SYSTEM_PROMPT_LENGTH = 4000
CHAT_MAX_MODEL_LENGTH = 128
CHAT_MAX_FEEDBACK_COMMENT_LENGTH = 1000
CHAT_MAX_FEEDBACK_TYPE_CODE_LENGTH = 64
CHAT_MAX_FEEDBACK_TYPE_LABEL_LENGTH = 64
CHAT_MAX_FEEDBACK_TYPE_DESCRIPTION_LENGTH = 500
CHAT_MAX_FEEDBACK_HANDLER_KEY_LENGTH = 64
CHAT_MAX_FEEDBACK_ADMIN_NOTE_LENGTH = 1000
CHAT_MAX_FEEDBACK_EVAL_NOTE_LENGTH = 1000
CHAT_DEFAULT_TOP_K = 10
CHAT_MAX_TOP_K = 50
CHAT_HISTORY_MESSAGE_LIMIT = 12

CHAT_RUN_MODE_LLM_CHAT = "llm_chat"
CHAT_RUN_MODE_KNOWLEDGE_RAG = "knowledge_rag"
CHAT_RUN_MODE_FILE_CHAT = "file_chat"
CHAT_RUN_MODE_AUTO = "auto"

CHAT_MESSAGE_ROLE_USER = "user"
CHAT_MESSAGE_ROLE_ASSISTANT = "assistant"
CHAT_MESSAGE_ROLE_SYSTEM = "system"

CHAT_MESSAGE_STATUS_SUCCESS = "success"
CHAT_MESSAGE_STATUS_FAILED = "failed"

CHAT_STREAM_EVENT_STARTED = "started"
CHAT_STREAM_EVENT_PARSING = "parsing"
CHAT_STREAM_EVENT_RETRIEVING = "retrieving"
CHAT_STREAM_EVENT_CITATIONS = "citations"
CHAT_STREAM_EVENT_DELTA = "delta"
CHAT_STREAM_EVENT_COMPLETED = "completed"
CHAT_STREAM_EVENT_FAILED = "failed"

CHAT_DEFAULT_SYSTEM_PROMPT = "你是企业 AI 助手，请给出准确、清晰、简洁的回答。"
CHAT_RAG_SYSTEM_PROMPT = (
    "你是企业知识库助手。请优先根据提供的知识库片段回答。"
    "如果知识库片段不足以回答，请明确说明无法从当前知识库确认。"
)
CHAT_NO_EVIDENCE_ANSWER = "当前知识库未找到相关内容。"
CHAT_FILE_SYSTEM_PROMPT = (
    "你是企业会话文件助手。请只根据本次会话上传的文件片段回答。"
    "如果文件片段不足以回答，请明确说明无法从当前文件确认。"
)
CHAT_FILE_NO_EVIDENCE_ANSWER = "无法从当前文件确认。"

CHAT_FILE_PARSE_MODE_NORMAL = "normal"
CHAT_FILE_PARSE_STATUS_PENDING = "pending"
CHAT_FILE_PARSE_STATUS_SUCCESS = "success"
CHAT_FILE_PARSE_STATUS_FAILED = "failed"
CHAT_FILE_PARSE_STATUS_EXPIRED = "expired"
CHAT_FILE_PROVIDER_MARKDOWN = "markdown"
CHAT_FILE_MARKDOWN_EXTENSIONS = frozenset({"md", "markdown"})
CHAT_FILE_SUPPORTED_EXTENSIONS = frozenset({"pdf", "doc", "docx", *CHAT_FILE_MARKDOWN_EXTENSIONS})
CHAT_FILE_CHUNK_TARGET_CHARS = 1600
CHAT_FILE_CHUNK_OVERLAP_CHARS = 180
CHAT_FILE_MAX_CHUNKS_PER_FILE = 300
CHAT_FILE_MAX_CANDIDATE_CHUNKS = 50

CHAT_SESSION_SOURCE_CHAT = "chat"
CHAT_SESSION_SOURCE_PUBLIC_SHARE = "public_share"
CHAT_PUBLIC_USER_ID = 0
CHAT_SHARE_DEFAULT_RATE_LIMIT_WINDOW_SECONDS = 60
CHAT_SHARE_DEFAULT_RATE_LIMIT_MAX_REQUESTS = 20

CHAT_FEEDBACK_RATING_LIKE = "like"
CHAT_FEEDBACK_RATING_DISLIKE = "dislike"

CHAT_FEEDBACK_STATUS_OPEN = "open"
CHAT_FEEDBACK_STATUS_REVIEWED = "reviewed"
CHAT_FEEDBACK_STATUS_RESOLVED = "resolved"
CHAT_FEEDBACK_STATUS_IGNORED = "ignored"

CHAT_FEEDBACK_TYPE_CITATION_ERROR = "citation_error"
CHAT_FEEDBACK_TYPE_INCOMPLETE = "incomplete"
CHAT_FEEDBACK_TYPE_HALLUCINATION = "hallucination"
CHAT_FEEDBACK_TYPE_OTHER = "other"
CHAT_FEEDBACK_HANDLER_NOOP = "noop"

__all__ = [
    "CHAT_DEFAULT_APP_NAME",
    "CHAT_DEFAULT_PAGE_SIZE",
    "CHAT_DEFAULT_SYSTEM_PROMPT",
    "CHAT_DEFAULT_TOP_K",
    "CHAT_FEEDBACK_HANDLER_NOOP",
    "CHAT_FEEDBACK_RATING_DISLIKE",
    "CHAT_FEEDBACK_RATING_LIKE",
    "CHAT_FEEDBACK_STATUS_IGNORED",
    "CHAT_FEEDBACK_STATUS_OPEN",
    "CHAT_FEEDBACK_STATUS_RESOLVED",
    "CHAT_FEEDBACK_STATUS_REVIEWED",
    "CHAT_FEEDBACK_TYPE_CITATION_ERROR",
    "CHAT_FEEDBACK_TYPE_HALLUCINATION",
    "CHAT_FEEDBACK_TYPE_INCOMPLETE",
    "CHAT_FEEDBACK_TYPE_OTHER",
    "CHAT_FILE_CHUNK_OVERLAP_CHARS",
    "CHAT_FILE_CHUNK_TARGET_CHARS",
    "CHAT_FILE_MAX_CANDIDATE_CHUNKS",
    "CHAT_FILE_MAX_CHUNKS_PER_FILE",
    "CHAT_FILE_NO_EVIDENCE_ANSWER",
    "CHAT_FILE_MARKDOWN_EXTENSIONS",
    "CHAT_FILE_PARSE_MODE_NORMAL",
    "CHAT_FILE_PARSE_STATUS_EXPIRED",
    "CHAT_FILE_PARSE_STATUS_FAILED",
    "CHAT_FILE_PARSE_STATUS_PENDING",
    "CHAT_FILE_PARSE_STATUS_SUCCESS",
    "CHAT_FILE_PROVIDER_MARKDOWN",
    "CHAT_FILE_SUPPORTED_EXTENSIONS",
    "CHAT_FILE_SYSTEM_PROMPT",
    "CHAT_HISTORY_MESSAGE_LIMIT",
    "CHAT_MAX_MESSAGE_LENGTH",
    "CHAT_MAX_APP_DESCRIPTION_LENGTH",
    "CHAT_MAX_FEEDBACK_ADMIN_NOTE_LENGTH",
    "CHAT_MAX_FEEDBACK_COMMENT_LENGTH",
    "CHAT_MAX_FEEDBACK_EVAL_NOTE_LENGTH",
    "CHAT_MAX_FEEDBACK_HANDLER_KEY_LENGTH",
    "CHAT_MAX_FEEDBACK_TYPE_CODE_LENGTH",
    "CHAT_MAX_FEEDBACK_TYPE_DESCRIPTION_LENGTH",
    "CHAT_MAX_FEEDBACK_TYPE_LABEL_LENGTH",
    "CHAT_MAX_MODEL_LENGTH",
    "CHAT_MAX_PAGE_SIZE",
    "CHAT_MAX_PROJECT_NAME_LENGTH",
    "CHAT_MAX_SYSTEM_PROMPT_LENGTH",
    "CHAT_MAX_TITLE_LENGTH",
    "CHAT_MAX_TOP_K",
    "CHAT_MESSAGE_ROLE_ASSISTANT",
    "CHAT_MESSAGE_ROLE_SYSTEM",
    "CHAT_MESSAGE_ROLE_USER",
    "CHAT_MESSAGE_STATUS_FAILED",
    "CHAT_MESSAGE_STATUS_SUCCESS",
    "CHAT_NO_EVIDENCE_ANSWER",
    "CHAT_RAG_SYSTEM_PROMPT",
    "CHAT_PUBLIC_USER_ID",
    "CHAT_RUN_MODE_AUTO",
    "CHAT_RUN_MODE_FILE_CHAT",
    "CHAT_RUN_MODE_KNOWLEDGE_RAG",
    "CHAT_RUN_MODE_LLM_CHAT",
    "CHAT_SESSION_SOURCE_CHAT",
    "CHAT_SESSION_SOURCE_PUBLIC_SHARE",
    "CHAT_SHARE_DEFAULT_RATE_LIMIT_MAX_REQUESTS",
    "CHAT_SHARE_DEFAULT_RATE_LIMIT_WINDOW_SECONDS",
    "CHAT_STREAM_EVENT_CITATIONS",
    "CHAT_STREAM_EVENT_COMPLETED",
    "CHAT_STREAM_EVENT_DELTA",
    "CHAT_STREAM_EVENT_FAILED",
    "CHAT_STREAM_EVENT_PARSING",
    "CHAT_STREAM_EVENT_RETRIEVING",
    "CHAT_STREAM_EVENT_STARTED",
]
